version: '3'

tasks:
  test:
    cmds:
      - go test ./internal/... -v --failfast

  lint:
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin
      - $GOPATH/bin/golangci-lint run -v -c .golangci.yml ./...

  install:
    cmds:
      - go build -o $GOPATH/bin/argocd-mcp main.go
 
  install-argocd-mock:
    cmds:
      - go build -o $GOPATH/bin/argocd-mock test/e2e/argocd-mock/main.go

  test-e2e:
    deps:
      - install
      - install-argocd-mock
    env:
      # required for e2e tests:
      MCP_SERVER_LISTEN: localhost:50081
      MCP_SERVER_DEBUG: true
      ARGOCD_SERVER_LISTEN: localhost:50084
      ARGOCD_SERVER_TOKEN: secure-token
      ARGOCD_SERVER_DEBUG: true
    cmds:
     - go test github.com/codeready-toolchain/argocd-mcp/test/e2e/... -v -failfast

  build-image:
    cmds:
      - podman build -t argocd-mcp:latest . -f Containerfile.yaml
