version: '3'

tasks:
  test:
    cmds:
      - go test ./internal/... -v --failfast

  lint:
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin
      - $GOPATH/bin/golangci-lint run -v -c .golangci.yml ./...

  install:
    cmds:
      - go build -o $GOPATH/bin/argocd-mcp main.go

  e2e-tests:
    deps:
      - install
    env:
      # required for e2e tests:
      # - ARGOCD_SERVER_URL=https://...
      # - ARGOCD_SERVER_TOKEN=...
      # optional:
      # - ARGOCD_MCP_PORT=8080
      # - ARGOCD_MCP_DEBUG=true
    cmds:
      - go test ./e2e-tests/... -v --failfast

  build-image:
    cmds:
      - podman build -t argocd-mcp:latest . -f Containerfile.yaml
