name: cd
on:
  push:
    branches:
      - master
  pull_request: # for manual testing
    branches:
      - master

jobs:
  build-image:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Task
        uses: arduino/setup-task@v2
          
      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: argocd-mcp
          tags: latest ${{ github.sha }}
          containerfiles: Containerfile.yaml

      - name: Push to quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
            image: ${{ steps.build-image.outputs.image }}
            tags: ${{ steps.build-image.outputs.tags }}
            registry: quay.io/codeready-toolchain/argocd-mcp
            username: 
            password: ${{ secrets.QUAY_TOKEN }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"